alias k9sr="k9s --readonly"
alias af="alias-finder -l"
alias kctx="kubectx"
alias mrup="mr -j10 -q up"
alias mrst="mr -j10 -m status"
alias myscrcpy="scrcpy --stay-awake --turn-screen-off --video-codec=h265 --max-size=1920 --max-fps=60 --no-audio --keyboard=uhid"
